FROM linuxmintd/mint18-amd64:latest

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update
RUN apt-get install libopenmpi-dev gmsh -y

RUN rm -rf /var/lib/apt/lists/*

CMD ["bash", "/app/run.sh"]
